- .gitignore
- SDG_11.2.1.ipynb
- modules.py
Solves issue 22. Correct Naptan data is now in the dataframe
> Imporrt naptan#22

- SDG_11.2.1.ipynb
correcting to Eastings and Northings as the X and Y variables respectively. Also crs from issue 14 should be fixed
> corrections and fixing crs

- SDG_11.2.1.ipynb
- modules.py
Working: filtering b'ham stops, joining b'ham polygon, buffering stops by 5km. Next todo: dissolve(?) buffered stops for service area. Interects points of populations centroids, with polygons of service area.
> Many things working now.

- SDG_11.2.1_main.py
Quite happy that the population data for Birmingham is already in a dataframe as bham_pop_df. I summed the population and it came very close to the actual population estimate of Birmingham. The tests were carried out in a jupyter notebook as a scratchpad which has not been committed. 
The small changes in the of SDG_11.2.1_main.py code were just a couple of things to tidy up and nothing actually to do with this ticket. Only making a PR to close the ticket.
Closes #3
> B'ham population already present

- SDG_11.2.1_main.py
This looks good to merge
Closes #15
> Got the output area boundaries into df

- SDG_11.2.1_main.py
Happy with the performance of this. Puts ages into buckets quickly. 
Closes #7
> Age buckets #7

- requirements.txt
The code seems to run fine with a much cleaned-up requirements text. I have left some of the old version numbers in there as comments just in case I need to revert
> Clean requests

- SDG_11.2.1_main.py
- data_ingest.py
- geospatial_mods.py
This completes the service area calculation and population count within that service area. 
Closes #69
> Brum calculation and population count

- SDG_11.2.1_main.py
- data_transform.py
Disaggregation by age is now working for B'ham.
> Disaggregation by age is now working

- SDG_11.2.1_main.py
> disability data imported to df

- SDG_11.2.1_main.py
Got the disability data into the population dataframe. And cleaned up some of the column titles. 
closes #57
> Disability data is now merged with main population df

- SDG_11.2.1_main.py
Imported and cleaned up col headers
Closes #79
> Sex by geog #58

- SDG_11.2.1_main.py
- data_transform.py
Seems to work for disaggregating sex. Need to QA numbers. 
Closes #3
> Disagg sex #3

- SDG_11.2.1_main.py
Seems to be working now. Not actually that much changed in the code but it has taken quite a bit of investigation in to the data. 
Closes #44
> Disability disagg #5

- SDG_11.2.1_main.py
- data_transform.py
I will need to refactor this later, so I have made a new issue to do this. https://github.com/ONSdigital/SDG_11.2.1/issues/95
Closes #43
> Disag urban #43

- SDG_11.2.1_main.py
- config.yaml
- data_ingest.py
- data_transform.py
- requirements.txt
Creating a draft PR to detail the issues around this code commit.
> Data import optimisation

- SDG_11.2.1_main.py
- config.yaml
- data_ingest.py
- data_transform.py
- geospatial_mods.py
Just working the linted code back into the main ticket I am working on at the moment. Worked on linting as #97 is blocked currently.
> Commit after massive code lint

- config.yaml
> Adding the config, otherwise this code won't run

- SDG_11.2.1_main.py
- config.yaml
- data_ingest.py
- data_transform.py
- geospatial_mods.py
Includes the changes for the disability proportion calculations and the linting/tidying
> Disability proportion #97

- SDG_11.2.1_main.py
> Disabilities calculation #113

- geospatial_mods.py
> deleting another junk func

- SDG_11.2.1_main.py
- config.yaml
- data_ingest.py
- database_mods.py
Solves #128 
All the results being calculated are now for 2019.
> Make sure all of the data being used is of the same year #128

- SDG_11.2.1_main.py
- config.yaml
Changes:
- Year can be chosen via config yaml
- 
Closes #128
> Calculates Whole Nation for Single Year

- SDG_11.2.1_main.py
- data_output.py
- data_transform.py
- This should handle zeros in dataframe as we discussed in a meeting about #153 
- Outputs string "None" for percentages instead of blanks as a requirement from SDG team
Merging back into the branch for #112 because that's where I branched from.
closes #153
> Handle zeros #153

- data_output.py
> Fix #179. Col headers swapped.

- SDG_11.2.1_main.py
- config.yaml
- data_transform.py
> Inactive stops #178

- SDG_11.2.1_main.py
- config.yaml
- data_ingest.py
- data_output.py
- data_transform.py
- send_file_test.txt
-This tickets look to retrieve stops data from the [NaPTAN wesbite.](https://naptan.api.dft.gov.uk/swagger/index.html) and save in the data folder, then as a feather.
-Downloads data and saves as feather if the local copy of stops data is more then 28 days old.
> Use naptan api #183

- README.md
I have finished updating the README.md with new documentation and linked tutorials that I found to be useful. Happy for suggestions or if it needs further updating.
> Document env #134

- SDG_11.2.1_main.py
- config.yaml
- data_transform.py
Draft pull request to see changes.
> Adding 'transport capacity' column

- SDG_11.2.1_main.py
- data_transform.py
> Create non disabled data 173

- SDG_11.2.1_main.py
- ftp_get_files_logic.py
I think the bug was to down to the formatting of paths with "//" and "/". Perhaps Mark was using an OS which had different paths? I've tried to use the os library where possible, so hopefully consistent going forward.
> fixing bug for ftp

- README.md
- main thing is to mention that ONS machines will not work with this script
- changed title from "Running the script" to "For Developers"
> Updating the "For Developers" section

- SDG_11.2.1_main.py
This randomly selects an LA to process from issue #215
> random selection of LA to process

- data_ingest.py
> fixing stop bug

- SDG_scotland.py
- data_ingest.py
> fixing stirling error

- SDG_11.2.1_main.py
> oa_la_lookup with os.path.join

- SDG_NI.py
- config.yaml
- data_ingest.py
This is to read in bus/train stop data for Northern Ireland. No data needed to be downloaded as (hopefully) the API will download this as part of the script.
> 270 read northern ireland transport data

- SDG_scotland.py
Closes #263 . 
Here is an example of what it outputted:
Any feedback is welcome!
> 263 produce sex pop estimates scotland

- data_output.py
This closes #206 
Example outputs can be found in #206
> adding in extra row for total served+unserved pop

- SDG_11.2.1_main.py
- SDG_bus_timetable.py
- SDG_scotland.py
- config.yaml
- data_ingest.py
- data_output.py
- data_transform.py
Disability data is now in the Scotland results dataframe. Let me know if you have any questions or are struggling with accessing the data.
**Note: The ordering of the dataframe is currently incorrect. This will be fixed when we have all disaggregations and can use the `do.reorder_final_df` function**
Outputted data frame below:
> 264 scotland by disability status

- SDG_NI.py
Closes #288. 
Both sources are read in and they should only read in the correct columns required (e.g. the year we need for pop estimates, and sex for the census results). 
The mid-year population estimates need to be saved in data/population_estimates and the census data (KS101_NI) needs to be saved in data/. Both are saved in Sync under the correct folder names.
Anything that you think could be improved or anything that needs to be added, let me know!
> 288 source and read in ni population data

- SDG_NI.py
- config.yaml
- data_ingest.py
Closes #309 .
This has had to be reworked just to get the data from the URL. I have taken this approach so that the data does not need to be stored in Sync. The `read_ni_stops` function has been updated now so that it reads the data in locally and, if it doesn't exist, it saves the data locally and reads it in.  Any comments are welcome!
> 309 get latest ni stops data

- SDG_NI.py
> read in centroid-data-ni

- SDG_NI.py
Closes #320 .
I have put the data that is required in SYNC under data/oa_la_mapping/NI .
> 320 read in la to small areas mapper

- SDG_11.2.1_main.py
- SDG_scotland.py
- data_ingest.py
- data_transform.py
This produces new estimates for transport accessibility disaggregated by urban/rural population.
The new data source is contained within data/urban_rural/scotland/
and can be downloaded [here](https://www.isdscotland.org/Products-and-Services/GPD-Support/Geography/Urban-Rural-Classification/).
I have uploaded these to the sync website.
I will wait for #287 to be closed before merging. There are likely to be conflicts, so I will solve them after that is merged then request a review from @paigeh1 afterwards.
Closes #249
> 67 find the urbanrural classification data by output area for scotland

- docs/source/write_up.md
Simple change to add Mark to the acknowledgements
> Mark added

- SDG_11.2.1_main.py
- SDG_bus_timetable.py
- SDG_train_timetable.py
- config.yaml
- data_ingest.py
- data_transform.py
- geospatial_mods.py
*Insert detailed bullet points about your changes here!*
*Insert any instructions to help the reviewer, e.g. "install new requirements from `requirements.txt`"*
*Let the reviewer know what data files are needed (to be grabbed from sync)
Fixes #
---
---
- additional tests that should be …
> 334 combine highlyservd bus train

- .gitignore
- .pre-commit-config.yaml
- requirements.txt
- .gitignore updated with many data file types to exclude from commits
- pre-commit yaml updated so it excludes any files with the same extensions (e.g. excel, csv....)
- pre-commit has been added to requirements.txt 
You will need to install new requirements from `requirements.txt`
No data files are needed but you might want to create a couple of dummy files, like "dummy.csv" or "dummy.feather" to see if you can commit them. 
Closes #326
I HAVE CREATED A TICKET, but don't have access to the Google doc to update it
---
---
- bugs that need fixing (does it work as expected? and …
> 326 pre commit hook for csv files

- SDG_scotland.py
- data_ingest.py
- data_transform.py
I have created an if statement in `data_transform.py` which handles any instances where the bins are larger than 90+. It should be generalised to work with any time that there are more bins over 90. I also changed the renaming of columns in `scotland.py`.
Fixes #
---
---
- additional tests …
> 340 change age bands in scotland

- data_transform.py
Fixes the data type check error in data transform.
Fixes #367 
- [x Code adheres to [DRY]([url](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)) 
N/A
N/A
N/A no new functions created.
---
---
- additional tests that should be implemented (do the tests effectively assure that it …
> First attempt at fix

- SDG_NI.py
Need to download the new KS101NI.csv file from Sync as I found that there were some minor issues that needed to be changed for the hard copy.
Fixes #371 
---
---
- additional tests that should be implemented (do the tests effectively assure that it
works correctly?)
- code style …
> added in sex disaggregation

- geospatial_mods.py
- main.py
I have added in ```capacity_type``` staying in ```main.py```. Also, the ```buffer_points``` function has now got error checking so that if a value of ```capacity_type``` is not high or low it will throw an error. 
Fixes #376 
---
---
- additional tests that should be implemented (do the …
> fixing so buffers are applied correctly

- SDG_NI.py
- SDG_scotland.py
- config.yaml
- data_ingest.py
- data_transform.py
- main.py
I have included the urban and rural data for Northern Ireland, and uploaded this to sync. A new folder will have to be created and stored here: data/urban_rural/NI/NI_urb_rur_class.csv
I have gone with the definition that we are making urban >10,000 and rural as <10,000. This means that bands A-D are urban and E-H are rural. 
I have also included a new function that does the urban rural classification across all 3 scripts
Fixes #316 
---
---
- alternative …
> 316 implement urbanrural classification for ni

- SDG_scotland.py
- geospatial_mods.py
A quick and dirty fix. When we undertake #381 I will properly check and remove all unneeded columns as per #380.
Duplicate `easting` and `northing` columns dropped when we undertake intersect between pwc and stops buffer. Reverted function back to original `find_points_in_poly` like eng, wales and NI use.
Removed `points_in_polygon` function as non longer used.
Tested on `Fife` and matches figures in QGIS (#352)
I have loads of linting errors but have left as wondering whether they are corrected in #369. 
Closes #374 
---
---
that it is likely to interact …
> 374 scotland output bug

- src/SDG_ni.py
I've added in a couple lines that will replace any comma in the census NI dataframe (for population) and will make these columns integers. 
Fixes #356 
---
---
- additional tests that should be implemented (do the tests effectively assure that it
works correctly?)
- code style improvements …
> Fix commas in pop count

- mkdocs.yml
*Insert detailed bullet points about your changes here!*
*Insert any instructions to help the reviewer, e.g. "install new requirements from `requirements.txt`"*
*Let the reviewer know what data files are needed (to be grabbed from sync)
Fixes #
---
---
- additional tests that should be …
> Pointing to correct developers docs
